"""Prompt 定义

包含所有 Agent 的系统提示词：
- master: MasterAgent 系统提示词
- experts: 专家 SubAgent 提示词
"""

from .master import MASTER_AGENT_SYSTEM_PROMPT
from .experts import (
    # 传统模式 prompts
    QUERY_PLANNER_PROMPT,
    SUMMARIZER_PROMPT,
    FACT_CHECKER_PROMPT,
    RESEARCHER_PROMPT,
    IMPACT_ASSESSOR_PROMPT,
    EXPERT_SUPERVISOR_PROMPT,
    # 结构化输出模式 prompts
    QUERY_PLANNER_PROMPT_STRUCTURED,
    SUMMARIZER_PROMPT_STRUCTURED,
    IMPACT_ASSESSOR_PROMPT_STRUCTURED,
    EXPERT_SUPERVISOR_PROMPT_STRUCTURED,
)

__all__ = [
    # Master
    "MASTER_AGENT_SYSTEM_PROMPT",
    # Traditional prompts
    "QUERY_PLANNER_PROMPT",
    "SUMMARIZER_PROMPT",
    "FACT_CHECKER_PROMPT",
    "RESEARCHER_PROMPT",
    "IMPACT_ASSESSOR_PROMPT",
    "EXPERT_SUPERVISOR_PROMPT",
    # Structured output prompts
    "QUERY_PLANNER_PROMPT_STRUCTURED",
    "SUMMARIZER_PROMPT_STRUCTURED",
    "IMPACT_ASSESSOR_PROMPT_STRUCTURED",
    "EXPERT_SUPERVISOR_PROMPT_STRUCTURED",
]

